import type { MachineDefinition, MachineId } from "@/types/game";

export const machines: Record<MachineId, MachineDefinition> = {
  cutter: {
    id: "cutter",
    name: "Cutter",
    description: "Slices material cleanly along a guide line.",
    instruction: "Drag across the line.",
    unlockLevel: 1,
    estimatedDurationSeconds: 3,
    baseDifficulty: 1,
    icon: "cutter",
    sfx: { loop: "cutLoop", resolve: "cutSliceWood" },
    implemented: true,
  },
  packager: {
    id: "packager",
    name: "Packager",
    description: "Seals the finished product in a box.",
    instruction: "Seal the package.",
    unlockLevel: 1,
    estimatedDurationSeconds: 3,
    baseDifficulty: 1,
    icon: "packager",
    sfx: { loop: "tapeLoop", resolve: "tapeSnap" },
    implemented: true,
  },
  stamper: {
    id: "stamper",
    name: "Stamper",
    description: "Presses a crisp logo into the product.",
    instruction: "Tap at the center.",
    unlockLevel: 3,
    estimatedDurationSeconds: 3,
    baseDifficulty: 2,
    icon: "stamper",
    sfx: { resolve: "stampThunk" },
    implemented: true,
  },
  polisher: {
    id: "polisher",
    name: "Polisher",
    description: "Buffs a dull surface to a bright shine.",
    instruction: "Polish every dull spot.",
    unlockLevel: 5,
    estimatedDurationSeconds: 8,
    baseDifficulty: 2,
    icon: "polisher",
    sfx: { loop: "polishLoop", resolve: "polishDone" },
    implemented: true,
  },
  paintBooth: {
    id: "paintBooth",
    name: "Paint Booth",
    description: "Sprays an even coat of colour.",
    instruction: "Spray an even coat. Keep moving.",
    unlockLevel: 8,
    estimatedDurationSeconds: 9,
    baseDifficulty: 3,
    icon: "paintBooth",
    sfx: { loop: "sprayLoop", resolve: "polishDone" },
    implemented: true,
  },
  assembler: {
    id: "assembler",
    name: "Assembler",
    description: "Builds each section from its parts, then the whole product.",
    instruction: "Snap each part into place.",
    unlockLevel: 12,
    estimatedDurationSeconds: 7,
    baseDifficulty: 3,
    icon: "assembler",
    sfx: { resolve: "snapIn" },
    implemented: true,
  },
  sorter: {
    id: "sorter",
    name: "Sorter",
    description: "Sends each piece to the bin that matches its shape.",
    instruction: "Send each piece to its bin.",
    unlockLevel: 10,
    estimatedDurationSeconds: 6,
    baseDifficulty: 3,
    icon: "sorter",
    sfx: { resolve: "sortDrop" },
    implemented: true,
  },
};

export const machineList: MachineDefinition[] = Object.values(machines).sort(
  (a, b) => a.unlockLevel - b.unlockLevel,
);
