import type { ThemeDefinition, ThemeId } from "@/types/game";

/**
 * Factory themes restyle the gameplay stage only (machines, background, particles).
 * They are independent from the light/dark UI mode, which lives in globals.css.
 */
export const themes: Record<ThemeId, ThemeDefinition> = {
  defaultFactory: {
    id: "defaultFactory",
    name: "Default Factory",
    description: "Rich blue, cyan highlights, warm gold accents.",
    unlockLevel: 1,
    cost: 0,
    vars: {
      "--fx-stage-a": "#eaf4ff",
      "--fx-stage-b": "#c9e2fb",
      "--fx-grid": "rgba(15, 85, 168, 0.08)",
      "--fx-ink": "#10233f",
      "--fx-ink-soft": "#4a6285",
      "--fx-machine": "#1667c4",
      "--fx-machine-light": "#3aa0f2",
      "--fx-machine-dark": "#0b2a63",
      "--fx-accent": "#ff9f0a",
      "--fx-accent-2": "#63d5ff",
      "--fx-belt": "#27425f",
      "--fx-belt-stripe": "#3a5a7d",
      "--fx-particle": "#63d5ff",
    },
  },
  freshMint: {
    id: "freshMint",
    name: "Fresh Mint",
    description: "Mint, aqua and clean white.",
    unlockLevel: 6,
    cost: 200,
    vars: {
      "--fx-stage-a": "#effcf7",
      "--fx-stage-b": "#c5f1e2",
      "--fx-grid": "rgba(22, 120, 100, 0.09)",
      "--fx-ink": "#19352f",
      "--fx-ink-soft": "#4b7067",
      "--fx-machine": "#1fa98b",
      "--fx-machine-light": "#5fdcc0",
      "--fx-machine-dark": "#0d5a4c",
      "--fx-accent": "#ffb347",
      "--fx-accent-2": "#7fe9ee",
      "--fx-belt": "#2f3b40",
      "--fx-belt-stripe": "#46565c",
      "--fx-particle": "#5fdcc0",
    },
  },
  nightShift: {
    id: "nightShift",
    name: "Night Shift",
    description: "Deep navy with neon cyan and violet.",
    unlockLevel: 8,
    cost: 400,
    vars: {
      "--fx-stage-a": "#16213d",
      "--fx-stage-b": "#0a1126",
      "--fx-grid": "rgba(120, 220, 255, 0.07)",
      "--fx-ink": "#e8f1ff",
      "--fx-ink-soft": "#9db2d6",
      "--fx-machine": "#3d4f8f",
      "--fx-machine-light": "#6a7fd0",
      "--fx-machine-dark": "#1b2450",
      "--fx-accent": "#a56bff",
      "--fx-accent-2": "#3fe6ff",
      "--fx-belt": "#05080f",
      "--fx-belt-stripe": "#1d2740",
      "--fx-particle": "#3fe6ff",
    },
  },
  sunsetShift: {
    id: "sunsetShift",
    name: "Sunset Shift",
    description: "Orange and coral over warm dusk purple.",
    unlockLevel: 10,
    cost: 600,
    vars: {
      "--fx-stage-a": "#ffe9d6",
      "--fx-stage-b": "#f9b9a3",
      "--fx-grid": "rgba(110, 40, 90, 0.08)",
      "--fx-ink": "#3a1d3f",
      "--fx-ink-soft": "#7a4a70",
      "--fx-machine": "#7b3fa0",
      "--fx-machine-light": "#b06fd0",
      "--fx-machine-dark": "#2a1a4a",
      "--fx-accent": "#ff7a3d",
      "--fx-accent-2": "#ffd166",
      "--fx-belt": "#2a1a3d",
      "--fx-belt-stripe": "#4a2f63",
      "--fx-particle": "#ffd166",
    },
  },
  candyLine: {
    id: "candyLine",
    name: "Candy Line",
    description: "Pastel pink, sky blue and cream.",
    unlockLevel: 12,
    cost: 800,
    vars: {
      "--fx-stage-a": "#fff6ea",
      "--fx-stage-b": "#ffd6e8",
      "--fx-grid": "rgba(180, 90, 150, 0.08)",
      "--fx-ink": "#4a2a4f",
      "--fx-ink-soft": "#8a6590",
      "--fx-machine": "#e77fb0",
      "--fx-machine-light": "#ffb3d4",
      "--fx-machine-dark": "#8f3f77",
      "--fx-accent": "#7cc8ff",
      "--fx-accent-2": "#c9a9ff",
      "--fx-belt": "#6b4a78",
      "--fx-belt-stripe": "#8a679a",
      "--fx-particle": "#c9a9ff",
    },
  },
};

export const themeList: ThemeDefinition[] = Object.values(themes).sort(
  (a, b) => a.unlockLevel - b.unlockLevel,
);
